SELECT PROFILE_IMG, MEMBER_NICKNAME,
SUBSTR(MEMBER_EMAIL, 0, INSTR(MEMBER_EMAIL, '@')-1) MEMBER_EMAIL,
TO_CHAR(ENROLL_DATE ,'YYYY.DD.MM') ENROLL_DATE, 
(SELECT MEMBER_LEVEL_IMG FROM MEMBER_LEVEL ml WHERE ml.MEMBER_LEVEL_NO = m.MEMBER_LEVEL_NO) MEMBER_LEVEL_IMG,
(SELECT MEMBER_LEVEL_NAME FROM MEMBER_LEVEL ml  WHERE ml.MEMBER_LEVEL_NO = m.MEMBER_LEVEL_NO) MEMBER_LEVEL_NAME 
,(SELECT AUTHORITY_IMG FROM AUTHORITY a  WHERE a.AUTHORITY_NO = m.AUTHORITY_NO) AUTHORITY_IMG
,(SELECT AUTHORITY_NAME FROM AUTHORITY a  WHERE a.AUTHORITY_NO = m.AUTHORITY_NO) AUTHORITY_NAME
,TO_CHAR(LOGIN_DATE ,'YYYY.DD.MM') LOGIN_DATE
,NVL(LOGHISTORY_COUNT,0) LOGHISTORY_COUNT
,NVL(BOARD_COUNT,0) BOARD_COUNT
,NVL(COMMENT_COUNT,0) COMMENT_COUNT
FROM "MEMBER" m 
LEFT JOIN (SELECT MAX(LOGIN_DATE) LOGIN_DATE,MEMBER_NO ,COUNT(LOGIN_DATE) LOGHISTORY_COUNT 
FROM LOGIN_HISTORY lh
GROUP BY MEMBER_NO
ORDER BY 2) USING(MEMBER_NO)
LEFT JOIN (SELECT COUNT(BOARD_NO) BOARD_COUNT ,MEMBER_NO 
FROM BOARD b 
GROUP BY MEMBER_NO
ORDER BY 2)
USING(MEMBER_NO)
LEFT JOIN (SELECT COUNT(COMMENT_NO) COMMENT_COUNT,MEMBER_NO 
FROM "COMMENT" c 
GROUP BY MEMBER_NO  
ORDER BY 2)
USING(MEMBER_NO)
WHERE  MEMBER_DEL_FL IN ('N','Y')
ORDER BY MEMBER_NICKNAME;

INSERT INTO LOGIN_HISTORY VALUES(SEQ_LOG_HISTORY_NO.NEXTVAL,DEFAULT,1);
SELECT * FROM LOGIN_HISTORY lh;

SELECT * FROM MEMBER_LEVEL ml;
SELECT * FROM AUTHORITY a ; 
SELECT * FROM "MEMBER" m;
SELECT * FROM BOARD b ;
SELECT * FROM "COMMENT" c ;

SELECT LOGIN_DATE,MEMBER_NO FROM "MEMBER" m
LEFT JOIN LOGIN_HISTORY USING(MEMBER_NO);

SELECT MAX(LOGIN_DATE) LOGIN_DATE,MEMBER_NO,COUNT(LOGIN_DATE) LOGHISTORY_COUNT  
FROM LOGIN_HISTORY lh
GROUP BY MEMBER_NO
ORDER BY 2;

SELECT COUNT(BOARD_NO) BOARD_COUNT ,MEMBER_NO 
FROM BOARD b 
GROUP BY MEMBER_NO
ORDER BY 2;


SELECT NVL(COUNT(COMMENT_NO),0) COMMENT_COUNT,MEMBER_NO 
FROM "COMMENT" c 
GROUP BY MEMBER_NO  
ORDER BY 2;

SELECT COUNT(*) FROM "MEMBER" m
WHERE MEMBER_DEL_FL IN ('N','Y');

INSERT INTO "MEMBER" VALUES(SEQ_MEMBER_NO.NEXTVAL,'user11@never.com','$2a$10$5QmOwkVwr3Ck87jdsIkdse00zhjAqfnApu7ogmEOP1boSa9e2Yvoe','유저십일',NULL,'/resources/images/main/철수2.png',SYSDATE,DEFAULT,2,2);
INSERT INTO "MEMBER" VALUES(SEQ_MEMBER_NO.NEXTVAL,'user12@never.com','$2a$10$5QmOwkVwr3Ck87jdsIkdse00zhjAqfnApu7ogmEOP1boSa9e2Yvoe','유저십이',NULL,'/resources/images/main/철수2.png',SYSDATE,DEFAULT,2,2);
