SELECT PROFILE_IMG, MEMBER_NICKNAME,
SUBSTR(MEMBER_EMAIL, 0, INSTR(MEMBER_EMAIL, '@')-1) MEMBER_EMAIL,
TO_CHAR(ENROLL_DATE ,'YYYY.MM.DD') ENROLL_DATE, 
(SELECT MEMBER_LEVEL_IMG FROM MEMBER_LEVEL ml WHERE ml.MEMBER_LEVEL_NO = m.MEMBER_LEVEL_NO) MEMBER_LEVEL_IMG,
(SELECT MEMBER_LEVEL_NAME FROM MEMBER_LEVEL ml  WHERE ml.MEMBER_LEVEL_NO = m.MEMBER_LEVEL_NO) MEMBER_LEVEL_NAME
,MEMBER_LEVEL_NO
,(SELECT AUTHORITY_IMG FROM AUTHORITY a  WHERE a.AUTHORITY_NO = m.AUTHORITY_NO) AUTHORITY_IMG
,(SELECT AUTHORITY_NAME FROM AUTHORITY a  WHERE a.AUTHORITY_NO = m.AUTHORITY_NO) AUTHORITY_NAME
,TO_CHAR(LOGIN_DATE ,'YYYY.MM.DD') LOGIN_DATE
,NVL(LOGHISTORY_COUNT,0) LOGHISTORY_COUNT
,NVL(BOARD_COUNT,0) BOARD_COUNT
,NVL(COMMENT_COUNT,0) COMMENT_COUNT
FROM "MEMBER" m 
LEFT JOIN (SELECT MAX(LOGIN_DATE) LOGIN_DATE,MEMBER_NO ,COUNT(LOGIN_DATE) LOGHISTORY_COUNT 
FROM LOGIN_HISTORY lh
GROUP BY MEMBER_NO
ORDER BY 2) USING(MEMBER_NO)
LEFT JOIN (SELECT COUNT(BOARD_NO) BOARD_COUNT ,MEMBER_NO 
FROM BOARD b 
GROUP BY MEMBER_NO
ORDER BY 2)
USING(MEMBER_NO)
LEFT JOIN (SELECT COUNT(COMMENT_NO) COMMENT_COUNT,MEMBER_NO 
FROM "COMMENT" c 
GROUP BY MEMBER_NO  
ORDER BY 2)
USING(MEMBER_NO)
WHERE  MEMBER_DEL_FL IN ('N','Y')
AND MEMBER_LEVEL_NO = 2
ORDER BY MEMBER_NICKNAME;

INSERT INTO LOGIN_HISTORY VALUES(SEQ_LOG_HISTORY_NO.NEXTVAL,DEFAULT,1);
SELECT * FROM LOGIN_HISTORY lh;

SELECT * FROM MEMBER_LEVEL ml;
SELECT * FROM AUTHORITY a ; 
SELECT * FROM "MEMBER" m;
SELECT * FROM BOARD b ;
SELECT * FROM "COMMENT" c ;

SELECT COUNT(*) FROM "MEMBER" m
WHERE MEMBER_DEL_FL IN ('N','S')
AND MEMBER_LEVEL_NO = 2;

SELECT LOGIN_DATE,MEMBER_NO FROM "MEMBER" m
LEFT JOIN LOGIN_HISTORY USING(MEMBER_NO);

SELECT MAX(LOGIN_DATE) LOGIN_DATE,MEMBER_NO,COUNT(LOGIN_DATE) LOGHISTORY_COUNT  
FROM LOGIN_HISTORY lh
GROUP BY MEMBER_NO
ORDER BY 2;

SELECT COUNT(BOARD_NO) BOARD_COUNT ,MEMBER_NO 
FROM BOARD b 
GROUP BY MEMBER_NO
ORDER BY 2;


SELECT NVL(COUNT(COMMENT_NO),0) COMMENT_COUNT,MEMBER_NO 
FROM "COMMENT" c 
GROUP BY MEMBER_NO  
ORDER BY 2;

SELECT COUNT(*) FROM "MEMBER" m
WHERE MEMBER_DEL_FL IN ('N','Y');

INSERT INTO "MEMBER" VALUES(SEQ_MEMBER_NO.NEXTVAL,'user11@never.com','$2a$10$5QmOwkVwr3Ck87jdsIkdse00zhjAqfnApu7ogmEOP1boSa9e2Yvoe','유저십일',NULL,'/resources/images/main/철수2.png',SYSDATE,DEFAULT,2,2);
INSERT INTO "MEMBER" VALUES(SEQ_MEMBER_NO.NEXTVAL,'user12@never.com','$2a$10$5QmOwkVwr3Ck87jdsIkdse00zhjAqfnApu7ogmEOP1boSa9e2Yvoe','유저십이',NULL,'/resources/images/main/철수2.png',SYSDATE,DEFAULT,2,2);

---------------------
SELECT BOARD_COUNT,MEMBER_NO FROM "MEMBER" m
LEFT JOIN (SELECT COUNT(BOARD_NO) BOARD_COUNT ,MEMBER_NO 
FROM BOARD b 
WHERE to_char(B_CREATE_DATE,'yyyy.mm.dd') BETWEEN to_char(add_months(sysdate,-1),'yyyy.mm.dd') AND to_char(SYSDATE,'yyyy.mm.dd')
GROUP BY MEMBER_NO
ORDER BY 2)
USING(MEMBER_NO)
WHERE MEMBER_DEL_FL IN ('N','S')
AND BOARD_COUNT >= 30
AND MEMBER_LEVEL_NO = 2;
---------------------
SELECT BOARD_COUNT,MEMBER_NO FROM "MEMBER" m
LEFT JOIN (SELECT COUNT(BOARD_NO) BOARD_COUNT ,MEMBER_NO 
FROM BOARD b 
GROUP BY MEMBER_NO
ORDER BY 2)
USING(MEMBER_NO)
WHERE MEMBER_DEL_FL IN ('N','S')
AND BOARD_COUNT >= 30
AND MEMBER_LEVEL_NO = 2;
-----------------------------
--게시글 수에 따라 
SELECT PROFILE_IMG, MEMBER_NICKNAME,
SUBSTR(MEMBER_EMAIL, 0, INSTR(MEMBER_EMAIL, '@')-1) MEMBER_EMAIL,
TO_CHAR(ENROLL_DATE ,'YYYY.MM.DD') ENROLL_DATE, 
(SELECT MEMBER_LEVEL_IMG FROM MEMBER_LEVEL ml WHERE ml.MEMBER_LEVEL_NO = m.MEMBER_LEVEL_NO) MEMBER_LEVEL_IMG,
(SELECT MEMBER_LEVEL_NAME FROM MEMBER_LEVEL ml  WHERE ml.MEMBER_LEVEL_NO = m.MEMBER_LEVEL_NO) MEMBER_LEVEL_NAME
,MEMBER_LEVEL_NO
,(SELECT AUTHORITY_IMG FROM AUTHORITY a  WHERE a.AUTHORITY_NO = m.AUTHORITY_NO) AUTHORITY_IMG
,(SELECT AUTHORITY_NAME FROM AUTHORITY a  WHERE a.AUTHORITY_NO = m.AUTHORITY_NO) AUTHORITY_NAME
,TO_CHAR(LOGIN_DATE ,'YYYY.MM.DD') LOGIN_DATE
,NVL(LOGHISTORY_COUNT,0) LOGHISTORY_COUNT
,NVL(BOARD_COUNT,0) BOARD_COUNT
,NVL(COMMENT_COUNT,0) COMMENT_COUNT
FROM "MEMBER" m 
LEFT JOIN (SELECT MAX(LOGIN_DATE) LOGIN_DATE,MEMBER_NO ,COUNT(LOGIN_DATE) LOGHISTORY_COUNT 
FROM LOGIN_HISTORY lh
GROUP BY MEMBER_NO
ORDER BY 2) USING(MEMBER_NO)
LEFT JOIN (SELECT COUNT(BOARD_NO) BOARD_COUNT ,MEMBER_NO 
FROM BOARD b 
GROUP BY MEMBER_NO
ORDER BY 2)
USING(MEMBER_NO)
LEFT JOIN (SELECT COUNT(COMMENT_NO) COMMENT_COUNT,MEMBER_NO 
FROM "COMMENT" c 
GROUP BY MEMBER_NO  
ORDER BY 2)
USING(MEMBER_NO)
WHERE  MEMBER_DEL_FL IN ('N','Y')
AND BOARD_COUNT >= 30
AND MEMBER_LEVEL_NO = 2
ORDER BY MEMBER_NICKNAME;
-----------------------------------------------------------
----------------게시글 수에 따라 최근 한달
SELECT PROFILE_IMG, MEMBER_NICKNAME,
SUBSTR(MEMBER_EMAIL, 0, INSTR(MEMBER_EMAIL, '@')-1) MEMBER_EMAIL,
TO_CHAR(ENROLL_DATE ,'YYYY.MM.DD') ENROLL_DATE, 
(SELECT MEMBER_LEVEL_IMG FROM MEMBER_LEVEL ml WHERE ml.MEMBER_LEVEL_NO = m.MEMBER_LEVEL_NO) MEMBER_LEVEL_IMG,
(SELECT MEMBER_LEVEL_NAME FROM MEMBER_LEVEL ml  WHERE ml.MEMBER_LEVEL_NO = m.MEMBER_LEVEL_NO) MEMBER_LEVEL_NAME
,MEMBER_LEVEL_NO
,(SELECT AUTHORITY_IMG FROM AUTHORITY a  WHERE a.AUTHORITY_NO = m.AUTHORITY_NO) AUTHORITY_IMG
,(SELECT AUTHORITY_NAME FROM AUTHORITY a  WHERE a.AUTHORITY_NO = m.AUTHORITY_NO) AUTHORITY_NAME
,TO_CHAR(LOGIN_DATE ,'YYYY.MM.DD') LOGIN_DATE
,NVL(LOGHISTORY_COUNT,0) LOGHISTORY_COUNT
,NVL(BOARD_COUNT,0) BOARD_COUNT
,NVL(COMMENT_COUNT,0) COMMENT_COUNT
FROM "MEMBER" m 
LEFT JOIN (SELECT MAX(LOGIN_DATE) LOGIN_DATE,MEMBER_NO ,COUNT(LOGIN_DATE) LOGHISTORY_COUNT 
FROM LOGIN_HISTORY lh
GROUP BY MEMBER_NO
ORDER BY 2) USING(MEMBER_NO)
LEFT JOIN (SELECT COUNT(BOARD_NO) BOARD_COUNT ,MEMBER_NO 
FROM BOARD b 
WHERE to_char(B_CREATE_DATE,'yyyy.mm.dd') BETWEEN to_char(add_months(sysdate,-1),'yyyy.mm.dd') AND to_char(SYSDATE,'yyyy.mm.dd')
GROUP BY MEMBER_NO
ORDER BY 2)
USING(MEMBER_NO)
LEFT JOIN (SELECT COUNT(COMMENT_NO) COMMENT_COUNT,MEMBER_NO 
FROM "COMMENT" c 
GROUP BY MEMBER_NO  
ORDER BY 2)
USING(MEMBER_NO)
WHERE  MEMBER_DEL_FL IN ('N','Y')
AND BOARD_COUNT >= 30
AND MEMBER_LEVEL_NO = 2
ORDER BY MEMBER_NICKNAME;

---------------------------------
(SELECT BOARD_COUNT FROM "MEMBER" m
LEFT JOIN (SELECT COUNT(BOARD_NO) BOARD_COUNT ,MEMBER_NO 
FROM BOARD b 
GROUP BY MEMBER_NO
ORDER BY 2)
USING(MEMBER_NO)
WHERE MEMBER_DEL_FL IN ('N','S')
AND MEMBER_LEVEL_NO = 2) >= 30
-----------------------------------------------------------------------------
---------------------------------------------------------------
--댓글 수에 따라 멤버
SELECT COUNT(*) 
FROM (SELECT COMMENT_COUNT, MEMBER_NO ,MEMBER_LEVEL_NO
FROM (SELECT NVL(COMMENT_COUNT,0) COMMENT_COUNT, MEMBER_NO ,MEMBER_LEVEL_NO
FROM "MEMBER" m
LEFT JOIN (SELECT COUNT(COMMENT_NO) COMMENT_COUNT,MEMBER_NO 
FROM "COMMENT" c 
<if test ="periodOption == 1">
	WHERE to_char(C_CREATE_DATE,'yyyy.mm.dd') BETWEEN to_char(add_months(sysdate,-1),'yyyy.mm.dd') AND to_char(SYSDATE,'yyyy.mm.dd')
</if>
GROUP BY MEMBER_NO  
ORDER BY 2)
USING(MEMBER_NO)
WHERE MEMBER_DEL_FL IN ('N','S'))
<where>
	<if test ="aboveOption == 1">
		COMMENT_COUNT <![CDATA[>=]]> 0
	</if>
	<if test ="aboveOption == 0">
		COMMENT_COUNT <![CDATA[<=]]> 0
	</if>
	
	<if test ="memberLevelNo != null">
		AND MEMBER_LEVEL_NO = 2)
	</if>
</where>

--------------------------------------------------
---------------------------------------------------------------
--댓글 수에 따라 멤버
SELECT COUNT(*) 
FROM (SELECT COMMENT_COUNT, MEMBER_NO ,MEMBER_LEVEL_NO
FROM (SELECT NVL(COMMENT_COUNT,0) COMMENT_COUNT, MEMBER_NO ,MEMBER_LEVEL_NO
FROM "MEMBER" m
LEFT JOIN (SELECT COUNT(COMMENT_NO) COMMENT_COUNT,MEMBER_NO 
FROM "COMMENT" c
WHERE to_char(C_CREATE_DATE,'yyyy.mm.dd') BETWEEN to_char(add_months(sysdate,-1),'yyyy.mm.dd') AND to_char(SYSDATE,'yyyy.mm.dd')
GROUP BY MEMBER_NO  
ORDER BY 2)
USING(MEMBER_NO)
WHERE MEMBER_DEL_FL IN ('N','S'))
WHERE COMMENT_COUNT >=0
);
--memberLevelNo(234)     0이면 등급 따지지 않고 전체 멤버 조회!!!!!
--periodOption(0 전체 1 최신)
--articleCountInput (댓글수)    aboveOption(1 이상 0 이하 )
--AND MEMBER_LEVEL_NO = 2
--------------------------------------------------
----------------------------------------------------------------------------

--------------------------------------------------------------------------
---------------------------------------------------------------------------
SELECT *
FROM 
(SELECT PROFILE_IMG, MEMBER_NICKNAME,
SUBSTR(MEMBER_EMAIL, 0, INSTR(MEMBER_EMAIL, '@')-1) MEMBER_EMAIL,
TO_CHAR(ENROLL_DATE ,'YYYY.MM.DD') ENROLL_DATE, 
(SELECT MEMBER_LEVEL_IMG FROM MEMBER_LEVEL ml WHERE ml.MEMBER_LEVEL_NO = m.MEMBER_LEVEL_NO) MEMBER_LEVEL_IMG,
(SELECT MEMBER_LEVEL_NAME FROM MEMBER_LEVEL ml  WHERE ml.MEMBER_LEVEL_NO = m.MEMBER_LEVEL_NO) MEMBER_LEVEL_NAME
,MEMBER_LEVEL_NO
,(SELECT AUTHORITY_IMG FROM AUTHORITY a  WHERE a.AUTHORITY_NO = m.AUTHORITY_NO) AUTHORITY_IMG
,(SELECT AUTHORITY_NAME FROM AUTHORITY a  WHERE a.AUTHORITY_NO = m.AUTHORITY_NO) AUTHORITY_NAME
,TO_CHAR(LOGIN_DATE ,'YYYY.MM.DD') LOGIN_DATE
,NVL(LOGHISTORY_COUNT,0) LOGHISTORY_COUNT
,NVL(BOARD_COUNT,0) BOARD_COUNT
,NVL(COMMENT_COUNT,0) COMMENT_COUNT
FROM "MEMBER" m 
LEFT JOIN (SELECT MAX(LOGIN_DATE) LOGIN_DATE,MEMBER_NO ,COUNT(LOGIN_DATE) LOGHISTORY_COUNT 
FROM LOGIN_HISTORY lh
GROUP BY MEMBER_NO
ORDER BY 2) USING(MEMBER_NO)
LEFT JOIN (SELECT COUNT(BOARD_NO) BOARD_COUNT ,MEMBER_NO 
FROM BOARD b 
GROUP BY MEMBER_NO
ORDER BY 2)
USING(MEMBER_NO)
LEFT JOIN (SELECT COUNT(COMMENT_NO) COMMENT_COUNT,MEMBER_NO 
FROM "COMMENT" c 
<if test ="periodOption == 1">
	WHERE to_char(C_CREATE_DATE,'yyyy.mm.dd') BETWEEN to_char(add_months(sysdate,-1),'yyyy.mm.dd') AND to_char(SYSDATE,'yyyy.mm.dd')
</if>
GROUP BY MEMBER_NO  
ORDER BY 2)
USING(MEMBER_NO)
WHERE  MEMBER_DEL_FL IN ('N','Y')
ORDER BY MEMBER_NICKNAME)
<where>
	<if test ="aboveOption == 1">
		COMMENT_COUNT <![CDATA[>=]]> 0
	</if>
	<if test ="aboveOption == 0">
		COMMENT_COUNT <![CDATA[<=]]> 0
	</if>
	
	<if test ="memberLevelNo != null">
		AND MEMBER_LEVEL_NO = 2)
	</if>
</where>

--memberLevelNo(234)     0이면 등급 따지지 않고 전체 멤버 조회!!!!!
--periodOption(0 전체 1 최신)
--articleCountInput (댓글수)    aboveOption(1 이상 0 이하 )
--AND MEMBER_LEVEL_NO = 2
SELECT COUNT(*) 
FROM (SELECT COMMENT_COUNT, MEMBER_NO ,MEMBER_LEVEL_NO
FROM (SELECT NVL(COMMENT_COUNT,0) COMMENT_COUNT, MEMBER_NO ,MEMBER_LEVEL_NO
FROM "MEMBER" m
LEFT JOIN (SELECT COUNT(COMMENT_NO) COMMENT_COUNT,MEMBER_NO 
FROM "COMMENT" c 
<if test ="periodOption == 1">
	WHERE to_char(C_CREATE_DATE,'yyyy.mm.dd') BETWEEN to_char(add_months(sysdate,-1),'yyyy.mm.dd') AND to_char(SYSDATE,'yyyy.mm.dd')
</if>
GROUP BY MEMBER_NO  
ORDER BY 2)
USING(MEMBER_NO)
WHERE MEMBER_DEL_FL IN ('N','S'))
<where>
	<if test ="aboveOption == 1">
		COMMENT_COUNT <![CDATA[>=]]> 0
	</if>
	<if test ="aboveOption == 0">
		COMMENT_COUNT <![CDATA[<=]]> 0
	</if>
	
	<if test ="memberLevelNo != null">
		AND MEMBER_LEVEL_NO = 2)
	</if>
</where>
-----------------------------------------------------
---------------------------------------------------------
---최근 한달
SELECT *
FROM 
(SELECT PROFILE_IMG, MEMBER_NICKNAME,
SUBSTR(MEMBER_EMAIL, 0, INSTR(MEMBER_EMAIL, '@')-1) MEMBER_EMAIL,
TO_CHAR(ENROLL_DATE ,'YYYY.MM.DD') ENROLL_DATE, 
(SELECT MEMBER_LEVEL_IMG FROM MEMBER_LEVEL ml WHERE ml.MEMBER_LEVEL_NO = m.MEMBER_LEVEL_NO) MEMBER_LEVEL_IMG,
(SELECT MEMBER_LEVEL_NAME FROM MEMBER_LEVEL ml  WHERE ml.MEMBER_LEVEL_NO = m.MEMBER_LEVEL_NO) MEMBER_LEVEL_NAME
,MEMBER_LEVEL_NO
,(SELECT AUTHORITY_IMG FROM AUTHORITY a  WHERE a.AUTHORITY_NO = m.AUTHORITY_NO) AUTHORITY_IMG
,(SELECT AUTHORITY_NAME FROM AUTHORITY a  WHERE a.AUTHORITY_NO = m.AUTHORITY_NO) AUTHORITY_NAME
,TO_CHAR(LOGIN_DATE ,'YYYY.MM.DD') LOGIN_DATE
,NVL(LOGHISTORY_COUNT,0) LOGHISTORY_COUNT
,NVL(BOARD_COUNT,0) BOARD_COUNT
,NVL(COMMENT_COUNT,0) COMMENT_COUNT
FROM "MEMBER" m 
LEFT JOIN (SELECT MAX(LOGIN_DATE) LOGIN_DATE,MEMBER_NO ,COUNT(LOGIN_DATE) LOGHISTORY_COUNT 
FROM LOGIN_HISTORY lh
GROUP BY MEMBER_NO
ORDER BY 2) USING(MEMBER_NO)
LEFT JOIN (SELECT COUNT(BOARD_NO) BOARD_COUNT ,MEMBER_NO 
FROM BOARD b 
GROUP BY MEMBER_NO
ORDER BY 2)
USING(MEMBER_NO)
LEFT JOIN (SELECT COUNT(COMMENT_NO) COMMENT_COUNT,MEMBER_NO 
FROM "COMMENT" c
WHERE to_char(C_CREATE_DATE,'yyyy.mm.dd') BETWEEN to_char(add_months(sysdate,-1),'yyyy.mm.dd') AND to_char(SYSDATE,'yyyy.mm.dd')
GROUP BY MEMBER_NO  
ORDER BY 2)
USING(MEMBER_NO)
WHERE  MEMBER_DEL_FL IN ('N','Y')
ORDER BY MEMBER_NICKNAME)
WHERE COMMENT_COUNT >= 0
AND MEMBER_LEVEL_NO = 2;
------------------------------------------------------------















SELECT COMMENT_COUNT, MEMBER_NO
FROM (SELECT COMMENT_COUNT, MEMBER_NO ,MEMBER_LEVEL_NO
FROM (SELECT NVL(COMMENT_COUNT,0) COMMENT_COUNT, MEMBER_NO ,MEMBER_LEVEL_NO
FROM "MEMBER" m
LEFT JOIN (SELECT COUNT(COMMENT_NO) COMMENT_COUNT,MEMBER_NO 
FROM "COMMENT" c
WHERE to_char(C_CREATE_DATE,'yyyy.mm.dd') BETWEEN to_char(add_months(sysdate,-1),'yyyy.mm.dd') AND to_char(SYSDATE,'yyyy.mm.dd')
GROUP BY MEMBER_NO  
ORDER BY 2)
USING(MEMBER_NO)
WHERE MEMBER_DEL_FL IN ('N','S')));







AND COMMENT_COUNT >=0
AND MEMBER_LEVEL_NO = 2;
--------------------------------------------------
SELECT COUNT(BOARD_NO) BOARD_COUNT ,MEMBER_NO 
FROM BOARD b 
GROUP BY MEMBER_NO
ORDER BY 2;

SELECT BOARD_NO ,MEMBER_NO 
FROM BOARD b
WHERE to_char(B_CREATE_DATE,'yyyy.mm.dd') BETWEEN to_char(add_months(sysdate,-1),'yyyy.mm.dd') AND to_char(SYSDATE,'yyyy.mm.dd');

SELECT COUNT(BOARD_NO) BOARD_COUNT ,MEMBER_NO 
FROM BOARD b 
WHERE to_char(B_CREATE_DATE,'yyyy.mm.dd') BETWEEN to_char(add_months(sysdate,-1),'yyyy.mm.dd') AND to_char(SYSDATE,'yyyy.mm.dd')
GROUP BY MEMBER_NO
ORDER BY 2;

------------------------------------------------------------------------------------------------
--방문 수 상세 조회!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
--하기 싫다 집에 가고 싶다아아아앙아아아아아아ㅏ아아아아아아아아아아아아아아아아ㅏㅇ















