-- 전체글보기
SELECT BOARD_TITLE, READ_COUNT, NOTICE_FL,
	(SELECT COUNT(*) FROM "COMMENT" C
	WHERE C.BOARD_NO = B.BOARD_NO
	AND COMMENT_DEL_FL='N') COMMENT_COUNT
FROM "BOARD" B
WHERE NOT NOTICE_FL = 1
AND BOARD_DEL_FL = 'N'
ORDER BY BOARD_NO DESC;

SELECT * FROM BOARD;

SELECT * FROM BOARD WHERE NOTICE_FL = 2;


SELECT BOARD_NO, BOARD_TITLE, MEMBER_NICKNAME, READ_COUNT, B_CREATE_DATE,
	(SELECT COUNT(*) FROM "COMMENT" C
	WHERE C.BOARD_NO = B.BOARD_NO) COMMENT_COUNT,
	(SELECT IMG_PATH || IMG_RENAME FROM BOARD_IMG I
	WHERE IMG_ORDER = 0
	AND I.BOARD_NO = B.BOARD_NO) THUMBNAIL
FROM BOARD B
JOIN MEMBER USING(MEMBER_NO)
WHERE BOARD_CODE = 1
AND BOARD_DEL_FL = 'N'
ORDER BY BOARD_NO DESC;

SELECT BOARD_TITLE, READ_COUNT,
	(SELECT COUNT(*) FROM "COMMENT" C
	WHERE C.BOARD_NO = B.BOARD_NO) COMMENT_COUNT
FROM "BOARD" B
WHERE NOTICE_FL = 2
ORDER BY BOARD_NO DESC;

SELECT BOARD_TITLE, READ_COUNT,
			(SELECT COUNT(*) FROM "COMMENT" C
			WHERE C.BOARD_NO = B.BOARD_NO) COMMENT_COUNT
			FROM "BOARD" B
			WHERE BOARD_DEL_FL = 'N'
			ORDER BY BOARD_NO DESC;
			
SELECT BOARD_TITLE, READ_COUNT,
		(SELECT COUNT(*) FROM "COMMENT" C
		WHERE C.BOARD_NO = B.BOARD_NO) COMMENT_COUNT
	FROM "BOARD" B
	WHERE NOTICE_FL = 2
	ORDER BY BOARD_NO DESC;
	
SELECT *
FROM BOARD_IMG;

SELECT *
FROM BOARD_TYPE;

BEGIN
   FOR I IN 1..100 LOOP
      INSERT INTO BOARD 
      VALUES(SEQ_BOARD_NO.NEXTVAL,
            SEQ_BOARD_NO.CURRVAL || '번째 사진 게시글',
            SEQ_BOARD_NO.CURRVAL || '번째 사진 게시글입니다.<br> 게시글 샘플입니다',
            DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, 
            FLOOR(DBMS_RANDOM.VALUE(6,17)), 12, DEFAULT);
   END LOOP;
END;

SELECT * FROM BOARD WHERE BOARD_CODE = 12;

INSERT INTO BOARD_IMG
VALUES(SEQ_IMG_NO.NEXTVAL, '/resources/images/board/',
	'20221116105843_00001.gif', '1.gif', 0, 714);

COMMIT;

SELECT BOARD_NO, BOARD_TITLE, MEMBER_NICKNAME, READ_COUNT, 
	(SELECT COUNT(*) FROM "COMMENT" C
	WHERE C.BOARD_NO =B.BOARD_NO) COMMENT_COUNT
FROM BOARD B
JOIN MEMBER USING(MEMBER_NO)
WHERE BOARD_DEL_FL = 'N'
AND BOARD_CODE = 12
ORDER BY BOARD_NO DESC;

SELECT * FROM BOARD_TYPE;

-- 회원수 조회
SELECT COUNT(MEMBER_NO)
FROM "MEMBER"
WHERE MEMBER_DEL_FL = 'N';

-- 방문자 수 조회
SELECT *
FROM LOGIN_HISTORY;


SELECT * FROM LOGIN_HISTORY WHERE DATE(LOGIN_DATE) = DATE(NOW());

SELECT * FROM LOGIN_HISTORY WHERE LOGIN_DATE  BETWEEN DATE_ADD(NOW(), INTERVAL -1 DAY ) AND NOW();

-- 당일 방문자 수
SELECT COUNT(*)
FROM LOGIN_HISTORY
WHERE TO_CHAR(LOGIN_DATE , 'YYYYMMDD' ) = TO_CHAR( SYSDATE, 'YYYYMMDD');

-- 전체 방문자 수
SELECT COUNT(*)전체 FROM LOGIN_HISTORY;

SELECT * FROM BOARD_TYPE WHERE BOARD_NAME = '여행 후기';

-- 댓글 랭킹
SELECT MEMBER_NICKNAME, MEMBER_NO, (SELECT COUNT(COMMENT_NO)
FROM "COMMENT"C WHERE M.MEMBER_NO=C.MEMBER_NO)COMMENT_COUNT
FROM "MEMBER" M
ORDER BY COMMENT_COUNT DESC;

-- 하루 전 댓글 랭킹
SELECT MEMBER_NICKNAME, MEMBER_NO, (SELECT COUNT(COMMENT_NO)
FROM "COMMENT"C
WHERE M.MEMBER_NO=C.MEMBER_NO
AND TO_CHAR(C.C_CREATE_DATE, 'YYYYMMDD' ) = TO_CHAR( SYSDATE-1, 'YYYYMMDD'))COMMENT_COUNT
FROM "MEMBER" M
ORDER BY COMMENT_COUNT DESC;

-- 하루 전 댓글 랭킹(0개 제외)
SELECT A.*
FROM (SELECT MEMBER_NICKNAME
MEMBER_NO,COUNT(C.MEMBER_NO) COMMENT_COUNT
FROM "MEMBER" M
JOIN "COMMENT" C ON M.MEMBER_NO = C.MEMBER_NO
WHERE TO_CHAR(C.C_CREATE_DATE, 'YYYYMMDD' ) = TO_CHAR( SYSDATE-1, 'YYYYMMDD')
GROUP BY M.MEMBER_NO, M.MEMBER_NICKNAME ) A
WHERE A.COMMENT_COUNT > 0;



-- 하루 전 게시글 랭킹
SELECT MEMBER_NICKNAME, MEMBER_NO, (SELECT COUNT(BOARD_NO)
FROM "BOARD"B
WHERE M.MEMBER_NO=B.MEMBER_NO
AND TO_CHAR(B.B_CREATE_DATE, 'YYYYMMDD' ) = TO_CHAR( SYSDATE-1, 'YYYYMMDD'))BOARD_COUNT
FROM "MEMBER" M
GROUP BY MEMBER_NICKNAME, MEMBER_NO HAVING COUNT(*) > 0
ORDER BY BOARD_COUNT DESC;

-- 하루 전 게시글 랭킹(0개 제외)
SELECT A.*
FROM (SELECT MEMBER_NICKNAME
MEMBER_NO,COUNT(B.MEMBER_NO) BOARD_COUNT
FROM "MEMBER" M
JOIN "BOARD" B ON M.MEMBER_NO = B.MEMBER_NO
WHERE TO_CHAR(B.B_CREATE_DATE, 'YYYYMMDD' ) = TO_CHAR( SYSDATE-1, 'YYYYMMDD')
GROUP BY M.MEMBER_NO, M.MEMBER_NICKNAME ) A
WHERE A.BOARD_COUNT > 0;

-- 하루 전 방문수 랭킹
SELECT MEMBER_NICKNAME, MEMBER_NO,
(SELECT COUNT(LOG_HISTORY_NO)
FROM "LOGIN_HISTORY" L
WHERE M.MEMBER_NO=L.MEMBER_NO
AND TO_CHAR(L.LOGIN_DATE, 'YYYYMMDD' ) = TO_CHAR( SYSDATE-1, 'YYYYMMDD'))LOGIN_COUNT
FROM "MEMBER" M
ORDER BY LOGIN_COUNT DESC;

-- 하루 전 방문수 랭킹(0번 제외)
SELECT A.*
FROM (
SELECT MEMBER_NICKNAME MEMBER_NO,COUNT(L.MEMBER_NO) LOGIN_COUNT
FROM "MEMBER" M
JOIN "LOGIN_HISTORY" L ON M.MEMBER_NO = L.MEMBER_NO
WHERE TO_CHAR(L.LOGIN_DATE, 'YYYYMMDD' ) = TO_CHAR( SYSDATE-1, 'YYYYMMDD')
GROUP BY M.MEMBER_NO, M.MEMBER_NICKNAME ) A
WHERE A.LOGIN_COUNT > 0
ORDER BY LOGIN_COUNT DESC;

SELECT * FROM LOGIN_HISTORY;

SELECT * FROM "COMMENT" c WHERE MEMBER_NO = 13;

-- 하루전 게시글 좋아요 랭킹
SELECT BOARD_NO,
(SELECT COUNT(MEMBER_NO)
FROM "BOARD" B
WHERE L.BOARD_NO = B.BOARD_NO
AND TO_CHAR(B.B_CREATE_DATE, 'YYYYMMDD') = TO_CHAR( SYSDATE-1, 'YYYYMMDD')) LIKE_COUNT
FROM "BOARD_LIKE" L
ORDER BY LIKE_COUNT DESC;


SELECT *
FROM BOARD B
JOIN BOARD_LIKE L ON B.BOARD_NO = L.BOARD_NO;

-- 하루전 로그인 랭킹
SELECT A.*
FROM (SELECT MEMBER_NICKNAME
MEMBER_NO,COUNT(L.MEMBER_NO) LOGIN_COUNT
FROM "MEMBER" M
JOIN "LOGIN_HISTORY" L ON M.MEMBER_NO = L.MEMBER_NO
WHERE TO_CHAR(L.LOGIN_DATE, 'YYYYMMDD' ) = TO_CHAR( SYSDATE-1, 'YYYYMMDD')
GROUP BY M.MEMBER_NO, M.MEMBER_NICKNAME ) A
WHERE A.LOGIN_COUNT > 0
ORDER BY LOGIN_COUNT DESC;

-- 일주일간 게시글 좋아요 랭킹
SELECT A.*
FROM(
SELECT BOARD_TITLE, COUNT(L.MEMBER_NO) LIKE_COUNT
FROM "BOARD" B
JOIN "BOARD_LIKE" L ON B.BOARD_NO = L.BOARD_NO
WHERE TO_CHAR(B.B_CREATE_DATE, 'YYYYMMDD') >= TO_CHAR( SYSDATE-7, 'YYYYMMDD')
GROUP BY B.BOARD_TITLE)A
WHERE A.LIKE_COUNT > 0
ORDER BY LIKE_COUNT DESC;

-- 일주일간 게시글 댓글 많이 달린 랭킹
SELECT A.*
FROM(
SELECT BOARD_TITLE, COUNT(C.COMMENT_NO) COMMENT_COUNT
FROM "BOARD" B
JOIN "COMMENT" C ON C.BOARD_NO = B.BOARD_NO
WHERE TO_CHAR(B.B_CREATE_DATE, 'YYYYMMDD') >= TO_CHAR( SYSDATE-7, 'YYYYMMDD')
AND TO_CHAR(C.C_CREATE_DATE, 'YYYYMMDD') >= TO_CHAR( SYSDATE-7, 'YYYYMMDD')
GROUP BY B.BOARD_TITLE)A
WHERE A.COMMENT_COUNT > 0
ORDER BY COMMENT_COUNT DESC;


SELECT BOARD_TITLE, READ_COUNT, NOTICE_FL,
	(SELECT COUNT(*) FROM "COMMENT" C
	WHERE C.BOARD_NO = B.BOARD_NO
	AND COMMENT_DEL_FL='N') COMMENT_COUNT
FROM "BOARD" B
WHERE NOT NOTICE_FL = 1
AND BOARD_DEL_FL = 'N'
ORDER BY BOARD_NO DESC;

-- 멤버소식 (방문)
SELECT M.MEMBER_NICKNAME, L.LOGIN_DATE
FROM LOGIN_HISTORY L
JOIN "MEMBER" M ON L.MEMBER_NO = M.MEMBER_NO
WHERE L.LOGIN_DATE = (SELECT MAX(LL.LOGIN_DATE)
						FROM LOGIN_HISTORY LL
						WHERE LL.MEMBER_NO = L.MEMBER_NO)
ORDER BY L.LOGIN_DATE DESC;

-- 멤버 소식(신입)
SELECT MEMBER_NICKNAME, ENROLL_DATE
FROM "MEMBER"
ORDER BY ENROLL_DATE DESC;

-- 최근게시글
SELECT *
FROM BOARD
WHERE BOARD_DEL_FL = 'N'
ORDER BY B_CREATE_DATE DESC;

-- 최근댓글
SELECT *
FROM "COMMENT" C
JOIN "BOARD" B ON(B.BOARD_NO=C.BOARD_NO)
WHERE COMMENT_DEL_FL = 'N'
ORDER BY C_CREATE_DATE DESC;

-- 지난주 게시글 랭킹 좋아요 (+코드,넘버 출력구문 추가)
SELECT A.*
FROM(
SELECT BOARD_TITLE, B.BOARD_NO, B.BOARD_CODE, COUNT(L.MEMBER_NO) LIKE_COUNT
FROM "BOARD" B
JOIN "BOARD_LIKE" L ON B.BOARD_NO = L.BOARD_NO
WHERE TO_CHAR(B.B_CREATE_DATE, 'YYYYMMDD') >= TO_CHAR( SYSDATE-7, 'YYYYMMDD')
GROUP BY B.BOARD_TITLE, B.BOARD_NO, B.BOARD_CODE)A
WHERE A.LIKE_COUNT > 0
ORDER BY LIKE_COUNT DESC

-- 지난주 게시글 랭킹 댓글 (+코드, 넘버 출력구문 추가)
SELECT A.*
FROM(
SELECT BOARD_TITLE, B.BOARD_NO, B.BOARD_CODE, COUNT(C.COMMENT_NO) COMMENT_COUNT
FROM "BOARD" B
JOIN "COMMENT" C ON C.BOARD_NO = B.BOARD_NO
WHERE TO_CHAR(B.B_CREATE_DATE, 'YYYYMMDD') >= TO_CHAR( SYSDATE-7, 'YYYYMMDD')
AND TO_CHAR(C.C_CREATE_DATE, 'YYYYMMDD') >= TO_CHAR( SYSDATE-7, 'YYYYMMDD')
GROUP BY B.BOARD_TITLE, B.BOARD_NO, B.BOARD_CODE)A
WHERE A.COMMENT_COUNT > 0
ORDER BY COMMENT_COUNT DESC


SELECT A.*
FROM (SELECT MEMBER_NICKNAME, M.MEMBER_NO, COUNT(L.MEMBER_NO) LOGIN_COUNT
FROM "MEMBER" M
JOIN "LOGIN_HISTORY" L ON M.MEMBER_NO = L.MEMBER_NO
WHERE TO_CHAR(L.LOGIN_DATE, 'YYYYMMDD' ) >= TO_CHAR( SYSDATE-7, 'YYYYMMDD')
GROUP BY M.MEMBER_NO, M.MEMBER_NICKNAME ) A
WHERE A.LOGIN_COUNT > 0
ORDER BY LOGIN_COUNT DESC;

SELECT A.*
FROM (SELECT MEMBER_NICKNAME, M.MEMBER_NO,
COUNT(C.MEMBER_NO) COMMENT_COUNT
FROM "MEMBER" M
JOIN "COMMENT" C ON M.MEMBER_NO = C.MEMBER_NO
WHERE TO_CHAR(C.C_CREATE_DATE, 'YYYYMMDD' ) >= TO_CHAR( SYSDATE-7, 'YYYYMMDD')
GROUP BY M.MEMBER_NO, M.MEMBER_NICKNAME ) A
WHERE A.COMMENT_COUNT > 0
ORDER BY COMMENT_COUNT DESC;

SELECT BOARD_NO, BOARD_CODE, BOARD_TITLE, MEMBER_NICKNAME, READ_COUNT, 
(SELECT COUNT(*) FROM "COMMENT" C
WHERE C.BOARD_NO =B.BOARD_NO
AND COMMENT_DEL_FL='N') COMMENT_COUNT
	,
  (SELECT IMG_PATH || IMG_RENAME 
  FROM (SELECT IMG_PATH, IMG_RENAME FROM BOARD_IMG I
  WHERE I.BOARD_NO = B.BOARD_NO
  ORDER BY IMG_NO) 
  WHERE ROWNUM = 1) THUMBNAIL
	FROM BOARD B
	JOIN MEMBER USING(MEMBER_NO)
	WHERE BOARD_DEL_FL = 'N'
AND BOARD_CODE = 12
ORDER BY BOARD_NO DESC

SELECT *
FROM CAFE_INFO;

SELECT PROFILE_IMG
FROM CAFE_INFO;

SELECT *
FROM CAFE_INFO
WHERE CAFE_NO = 1;

SELECT MEMBER_NO, MEMBER_NICKNAME MANAGER_NICKNAME
FROM "MEMBER"
WHERE MEMBER_LEVEL_NO = 0;

