-- 전체글보기
SELECT BOARD_TITLE, READ_COUNT, NOTICE_FL,
	(SELECT COUNT(*) FROM "COMMENT" C
	WHERE C.BOARD_NO = B.BOARD_NO) COMMENT_COUNT
FROM "BOARD" B
WHERE NOT NOTICE_FL = 1
AND BOARD_DEL_FL = 'N'
ORDER BY BOARD_NO DESC;

SELECT * FROM BOARD;

SELECT * FROM BOARD WHERE NOTICE_FL = 2;


SELECT BOARD_NO, BOARD_TITLE, MEMBER_NICKNAME, READ_COUNT, B_CREATE_DATE,
	(SELECT COUNT(*) FROM "COMMENT" C
	WHERE C.BOARD_NO = B.BOARD_NO) COMMENT_COUNT,
	(SELECT IMG_PATH || IMG_RENAME FROM BOARD_IMG I
	WHERE IMG_ORDER = 0
	AND I.BOARD_NO = B.BOARD_NO) THUMBNAIL
FROM BOARD B
JOIN MEMBER USING(MEMBER_NO)
WHERE BOARD_CODE = 1
AND BOARD_DEL_FL = 'N'
ORDER BY BOARD_NO DESC;

SELECT BOARD_TITLE, READ_COUNT,
	(SELECT COUNT(*) FROM "COMMENT" C
	WHERE C.BOARD_NO = B.BOARD_NO) COMMENT_COUNT
FROM "BOARD" B
WHERE NOTICE_FL = 2
ORDER BY BOARD_NO DESC;

SELECT BOARD_TITLE, READ_COUNT,
			(SELECT COUNT(*) FROM "COMMENT" C
			WHERE C.BOARD_NO = B.BOARD_NO) COMMENT_COUNT
			FROM "BOARD" B
			WHERE BOARD_DEL_FL = 'N'
			ORDER BY BOARD_NO DESC;
			
SELECT BOARD_TITLE, READ_COUNT,
		(SELECT COUNT(*) FROM "COMMENT" C
		WHERE C.BOARD_NO = B.BOARD_NO) COMMENT_COUNT
	FROM "BOARD" B
	WHERE NOTICE_FL = 2
	ORDER BY BOARD_NO DESC;
	
SELECT *
FROM BOARD_IMG;

SELECT *
FROM BOARD_TYPE;

BEGIN
   FOR I IN 1..100 LOOP
      INSERT INTO BOARD 
      VALUES(SEQ_BOARD_NO.NEXTVAL,
            SEQ_BOARD_NO.CURRVAL || '번째 사진 게시글',
            SEQ_BOARD_NO.CURRVAL || '번째 사진 게시글입니다.<br> 게시글 샘플입니다',
            DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, 
            FLOOR(DBMS_RANDOM.VALUE(6,17)), 12, DEFAULT);
   END LOOP;
END;

SELECT * FROM BOARD WHERE BOARD_CODE = 12;

INSERT INTO BOARD_IMG
VALUES(SEQ_IMG_NO.NEXTVAL, '/resources/images/board/',
	'20221116105843_00001.gif', '1.gif', 0, 714);

COMMIT;

SELECT BOARD_NO, BOARD_TITLE, MEMBER_NICKNAME, READ_COUNT, 
	(SELECT COUNT(*) FROM "COMMENT" C
	WHERE C.BOARD_NO =B.BOARD_NO) COMMENT_COUNT
FROM BOARD B
JOIN MEMBER USING(MEMBER_NO)
WHERE BOARD_DEL_FL = 'N'
AND BOARD_CODE = 12
ORDER BY BOARD_NO DESC;

SELECT * FROM BOARD_TYPE;

-- 방문자 수 조회
SELECT *
FROM LOGIN_HISTORY;


SELECT * FROM LOGIN_HISTORY WHERE DATE(LOGIN_DATE) = DATE(NOW());

SELECT * FROM LOGIN_HISTORY WHERE LOGIN_DATE  BETWEEN DATE_ADD(NOW(), INTERVAL -1 DAY ) AND NOW();

-- 당일 방문자 수
SELECT COUNT(*)
FROM LOGIN_HISTORY
WHERE TO_CHAR(LOGIN_DATE , 'YYYYMMDD' ) = TO_CHAR( SYSDATE, 'YYYYMMDD');

-- 전체 방문자 수
SELECT COUNT(*)전체 FROM LOGIN_HISTORY;

SELECT * FROM BOARD_TYPE WHERE BOARD_NAME = '여행 후기';

-- 댓글 랭킹
SELECT MEMBER_NICKNAME, MEMBER_NO, (SELECT COUNT(COMMENT_NO)
FROM "COMMENT"C WHERE M.MEMBER_NO=C.MEMBER_NO)COMMENT_COUNT
FROM "MEMBER" M
ORDER BY COMMENT_COUNT DESC;

-- 하루 전 댓글 랭킹
SELECT MEMBER_NICKNAME, MEMBER_NO, (SELECT COUNT(COMMENT_NO)
FROM "COMMENT"C
WHERE M.MEMBER_NO=C.MEMBER_NO
AND TO_CHAR(C.C_CREATE_DATE, 'YYYYMMDD' ) = TO_CHAR( SYSDATE-1, 'YYYYMMDD'))COMMENT_COUNT
FROM "MEMBER" M
ORDER BY COMMENT_COUNT DESC;

-- 하루 전 게시글 랭킹
SELECT MEMBER_NICKNAME, MEMBER_NO, (SELECT COUNT(BOARD_NO)
FROM "BOARD"B
WHERE M.MEMBER_NO=B.MEMBER_NO
AND TO_CHAR(B.B_CREATE_DATE, 'YYYYMMDD' ) = TO_CHAR( SYSDATE-1, 'YYYYMMDD'))BOARD_COUNT
FROM "MEMBER" M
ORDER BY BOARD_COUNT DESC;


SELECT * FROM "COMMENT" c WHERE MEMBER_NO = 13;
